from pydantic import BaseModel, Field
from typing import Any, Optional


# ------------------------------------------------------------------
# Standard query
# ------------------------------------------------------------------

class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Natural language research question")
    mode: str = Field("standard", description="Query mode: standard, hypothesis, compare")
    include_pubmed: bool = Field(False, description="Whether to include live PubMed results")


class ImageQueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Research question about the image")
    image_base64: str = Field(..., description="Base64-encoded image data")
    media_type: str = Field("image/jpeg", description="Image MIME type: image/jpeg, image/png, image/gif, image/webp")
    include_pubmed: bool = Field(False, description="Whether to include live PubMed results")


class RetrievedPropositionSchema(BaseModel):
    """A single proposition retrieved from the hybrid search pipeline."""
    text: str
    score: float = Field(0.0, description="RRF fusion score")
    rerank_score: float = Field(0.0, description="CrossEncoder reranking score")
    metadata: dict[str, Any] = Field(default_factory=dict)
    content_type: str = Field("text", description="text | image | table")
    image_hash: Optional[str] = Field(None, description="Content-addressed hash for retrieving the image via /images/{hash}")
    image_url: Optional[str] = Field(None, description="Convenience URL for the frontend to render the figure")
    table_markdown: Optional[str] = Field(None, description="Markdown rendering of the table, if content_type == 'table'")


class StructuredReasoning(BaseModel):
    """Structured scientific reasoning breakdown."""

    summary: str = Field("", description="Narrative summary of the mechanism or finding")
    key_entities: list[str] = Field(default_factory=list, description="Key entities and actors involved")
    key_mechanisms: list[str] = Field(default_factory=list, description="Key mechanisms and signaling mediators")
    pathways: list[str] = Field(default_factory=list, description="Key regulatory and signaling pathways")
    therapeutic_targets: list[str] = Field(default_factory=list, description="Druggable targets and approved therapeutics")
    open_questions: list[str] = Field(default_factory=list, description="Unresolved hypotheses and research gaps")
    genes: list[str] = Field(default_factory=list, description="Associated genetic loci and variants")
    topic_context: str = Field("", description="Domain-specific context and background")


class PubMedResult(BaseModel):
    """A PubMed article result."""
    pmid: str = ""
    title: str = ""
    abstract: str = ""
    authors: list[str] = Field(default_factory=list)
    journal: str = ""
    year: str = ""
    doi: str = ""
    citation: str = ""


class QueryResponse(BaseModel):
    answer: str = Field(..., description="Structured answer generated by the LLM service")
    sources: list[str] = Field(..., description="List of source references supporting the answer")
    reasoning: StructuredReasoning = Field(
        default_factory=StructuredReasoning,
        description="Structured scientific reasoning breakdown",
    )
    pubmed_articles: list[PubMedResult] = Field(
        default_factory=list,
        description="Live PubMed articles related to the query",
    )
    graph_context: Optional[dict[str, Any]] = Field(
        None, description="Knowledge graph subgraph context if available",
    )
    retrieved_propositions: list[RetrievedPropositionSchema] = Field(
        default_factory=list,
        description="Top propositions from the hybrid retrieval pipeline (for citation panel)",
    )
    model_used: str = Field("", description="LLM model that generated the answer")
    cost_usd: float = Field(0.0, description="Estimated cost of this query in USD")
    image_analysis: Optional[str] = Field(None, description="Claude vision observations extracted from an uploaded image")


# ------------------------------------------------------------------
# Comparative analysis
# ------------------------------------------------------------------

class CompareRequest(BaseModel):
    disease_a: str = Field(..., min_length=1, description="First disease to compare")
    disease_b: str = Field(..., min_length=1, description="Second disease to compare")


class CompareResponse(BaseModel):
    disease_a: dict[str, Any] = Field(..., description="Profile of disease A")
    disease_b: dict[str, Any] = Field(..., description="Profile of disease B")
    overlaps: dict[str, Any] = Field(..., description="Shared and unique features")
    similarity_score: float = Field(..., description="Overall mechanistic similarity (0-1)")
    summary: str = Field(..., description="Narrative comparison summary")


# ------------------------------------------------------------------
# Hypothesis generator
# ------------------------------------------------------------------

class HypothesisRequest(BaseModel):
    topic: str = Field(..., min_length=1, description="Research topic for hypothesis generation")
    max_hypotheses: int = Field(5, ge=1, le=10, description="Maximum hypotheses to generate")


class HypothesisEntry(BaseModel):
    hypothesis: str
    category: str
    rationale: str
    experimental_design: dict[str, Any]
    biomarkers: list[str]
    confounders: list[str]
    confidence: str
    supporting_evidence: list[str] = Field(default_factory=list)


class HypothesisResponse(BaseModel):
    topic: str
    hypotheses: list[HypothesisEntry]
    context: dict[str, Any]
    total_generated: int


# ------------------------------------------------------------------
# PubMed search
# ------------------------------------------------------------------

class PubMedSearchRequest(BaseModel):
    query: str = Field(..., min_length=1, description="PubMed search query")
    max_results: int = Field(10, ge=1, le=50, description="Maximum results to return")
    domain_enriched: bool = Field(False, description="Add domain-specific MeSH terms to query")


class PubMedSearchResponse(BaseModel):
    query: str
    articles: list[PubMedResult]
    interactions: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Extracted molecular interactions from abstracts",
    )
    total_found: int


# ------------------------------------------------------------------
# Knowledge graph
# ------------------------------------------------------------------

class GraphSubgraphRequest(BaseModel):
    seed_nodes: list[str] = Field(..., min_length=1, description="Nodes to center the subgraph on")
    hops: int = Field(2, ge=1, le=4, description="Number of hops to expand")


class InterventionRankRequest(BaseModel):
    target_node: str = Field(..., min_length=1, description="Target node to modulate")
    cell_type_context: Optional[str] = Field(None, description="Optional cell-type filter")
    top_k: int = Field(10, ge=1, le=50)


class CausalPropagateRequest(BaseModel):
    seed_scores: dict[str, float] = Field(..., description="Seed node scores (positive=activating, negative=inhibitory)")
    direction: str = Field("downstream", description="Propagation direction: downstream, upstream, or both")


# ------------------------------------------------------------------
# Disease dossiers
# ------------------------------------------------------------------

class CreateDossierRequest(BaseModel):
    name: str = Field(..., min_length=1, description="Dossier name")
    description: str = Field("", description="Dossier description")
    tags: list[str] = Field(default_factory=list)


class AddToDossierRequest(BaseModel):
    query: str = Field(..., min_length=1)
    response: dict[str, Any] = Field(..., description="Query response to save")
    notes: str = Field("", description="User notes for this entry")


class UpdateNotesRequest(BaseModel):
    notes: str = Field(..., description="Updated notes text")


# ------------------------------------------------------------------
# Document ingestion
# ------------------------------------------------------------------

class DocumentIngestResponse(BaseModel):
    filename: str
    propositions_indexed: int
    images_captioned: int
    tables_indexed: int = 0
    pages: int
    message: str = ""
