from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Natural language question about autoimmune biology")


class QueryResponse(BaseModel):
    answer: str = Field(..., description="Structured answer generated by the LLM service")
    sources: list[str] = Field(..., description="List of source references supporting the answer")
