from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Natural language question about autoimmune biology")


class StructuredReasoning(BaseModel):
    """Structured immune reasoning breakdown."""

    summary: str = Field("", description="Narrative summary of the immune mechanism")
    key_cells: list[str] = Field(default_factory=list, description="Key immune cell types involved")
    key_cytokines: list[str] = Field(default_factory=list, description="Relevant cytokines and signaling molecules")
    pathways: list[str] = Field(default_factory=list, description="Dysregulated immune pathways")
    therapeutic_targets: list[str] = Field(default_factory=list, description="Druggable targets and approved therapeutics")
    open_questions: list[str] = Field(default_factory=list, description="Unresolved hypotheses and research gaps")
    genes: list[str] = Field(default_factory=list, description="Associated genetic risk loci")
    disease_context: str = Field("", description="Disease-specific context and epidemiology")


class QueryResponse(BaseModel):
    answer: str = Field(..., description="Structured answer generated by the LLM service")
    sources: list[str] = Field(..., description="List of source references supporting the answer")
    reasoning: StructuredReasoning = Field(
        default_factory=StructuredReasoning,
        description="Structured immune reasoning breakdown",
    )
